import { createServer, type IncomingMessage, type ServerResponse } from "node:http";
import { exec } from "node:child_process";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { promisify } from "node:util";
import { defaultDesignDNA, designDNASchema, generateDesignBrief, type DesignDNA } from "@creative-ui/core";
import { visualReferenceCatalog } from "@creative-ui/lineage";

const execAsync = promisify(exec);
export type StudioOptions = { cwd: string; port?: number; open?: boolean };

async function loadDNA(cwd: string): Promise<DesignDNA> {
  try { const raw = await readFile(join(cwd, ".creative-ui", "design-dna.json"), "utf8"); return designDNASchema.parse(JSON.parse(raw)); }
  catch { return structuredClone(defaultDesignDNA); }
}
async function saveDNA(cwd: string, dna: DesignDNA) {
  const dir = join(cwd, ".creative-ui"); await mkdir(dir, { recursive: true });
  await Promise.all([writeFile(join(dir, "design-dna.json"), `${JSON.stringify(dna, null, 2)}\n`), writeFile(join(dir, "DESIGN.md"), generateDesignBrief(dna))]);
}
function sendJson(res: ServerResponse, value: unknown, status = 200) { res.writeHead(status, { "content-type": "application/json; charset=utf-8", "cache-control": "no-store" }); res.end(JSON.stringify(value)); }
async function readBody(req: IncomingMessage) { const chunks: Buffer[] = []; for await (const chunk of req) chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk)); return Buffer.concat(chunks).toString("utf8"); }
async function openBrowser(url: string) {
  const command = process.platform === "darwin" ? `open ${JSON.stringify(url)}` : process.platform === "win32" ? `start "" ${JSON.stringify(url)}` : `xdg-open ${JSON.stringify(url)}`;
  try { await execAsync(command); } catch { /* terminal URL is enough */ }
}

const page = String.raw`<!doctype html><html lang="en"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><title>Creative UI Studio</title><style>
:root{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;color:#111;background:#eee}*{box-sizing:border-box}body{margin:0}button,input,select,textarea{font:inherit}.shell{display:grid;grid-template-columns:310px minmax(0,1fr);min-height:100vh}.rail{position:sticky;top:0;height:100vh;overflow:auto;padding:24px;border-right:2px solid #111;background:#f7f7f2}.main{padding:32px;max-width:1200px}.brand{font-weight:900;font-size:22px;letter-spacing:-.04em}.muted{opacity:.58}.tabs{display:flex;gap:6px;flex-wrap:wrap;margin:22px 0}.tabs button,.chip,button{border:1.5px solid #111;background:transparent;padding:7px 9px;cursor:pointer}.tabs button.active,.chip.active,.primary{background:#111;color:#fff}.panel{display:none}.panel.active{display:block}.row{display:grid;grid-template-columns:170px 1fr 54px;gap:12px;align-items:center;margin:11px 0}.row input[type=range]{width:100%;accent-color:#111}.lineage{display:grid;grid-template-columns:repeat(auto-fill,minmax(240px,1fr));gap:10px}.ref{border:1.5px solid #111;padding:12px;background:#f7f7f2}.ref.selected{box-shadow:5px 5px 0 #111}.ref h3{font-size:14px;margin:0 0 7px}.ref small{display:block;opacity:.6;margin-bottom:8px}.ref p{font-family:ui-sans-serif,system-ui,sans-serif;font-size:13px;line-height:1.35}.ref .channels{font-size:11px;opacity:.7}.search{width:100%;padding:10px;border:1.5px solid #111;background:#fff;margin-bottom:14px}.concept{width:100%;min-height:82px;padding:10px;border:1.5px solid #111;background:#fff}.actions{display:flex;gap:8px;margin-top:22px}.status{margin-top:10px;font-size:12px}.preview{border:1.5px solid #111;background:#fff;padding:24px;margin-top:18px}.preview-grid{display:grid;grid-template-columns:2fr 1fr;gap:22px}.mass{min-height:180px;border:2px solid #111;padding:18px;display:flex;flex-direction:column;justify-content:space-between}.mass.alt{transform:translateY(24px)}.big{font-family:ui-sans-serif,system-ui,sans-serif;font-size:clamp(36px,6vw,86px);font-weight:900;line-height:.9;letter-spacing:-.06em}@media(max-width:760px){.shell{grid-template-columns:1fr}.rail{position:relative;height:auto;border-right:0;border-bottom:2px solid #111}.main{padding:20px}.preview-grid{grid-template-columns:1fr}.mass.alt{transform:none}.row{grid-template-columns:120px 1fr 48px}}
</style></head><body><div class="shell"><aside class="rail"><div class="brand">CREATIVE UI<br/>STUDIO</div><p class="muted">Direction before decoration.</p><div class="tabs"><button data-tab="intent" class="active">INTENT</button><button data-tab="axes">DNA</button><button data-tab="novelty">NOVELTY</button><button data-tab="lineage">LINEAGE</button></div><div><b>Composition</b><select id="composition" style="width:100%;margin-top:7px;padding:8px;border:1.5px solid #111"></select></div><div class="actions"><button id="save" class="primary">SAVE DNA</button><button id="reload">RELOAD</button></div><div id="status" class="status muted">connected locally</div></aside><main class="main"><section id="intent" class="panel active"><h1>Concept</h1><textarea id="concept" class="concept"></textarea><h2>Preview grammar</h2><div class="preview"><div class="preview-grid"><div class="mass"><span class="muted">PRIMARY MASS</span><div class="big" id="previewTitle">expressive<br/>interface</div><span>composition / hierarchy / rhythm</span></div><div class="mass alt"><span>SECONDARY</span><div id="previewMeta"></div><span class="muted">not a template</span></div></div></div></section><section id="axes" class="panel"><h1>Design DNA</h1><div id="axesRows"></div></section><section id="novelty" class="panel"><h1>Novelty budget</h1><p>Permission to experiment, not an obligation to make everything weird.</p><div id="noveltyRows"></div></section><section id="lineage" class="panel"><h1>Visual lineage</h1><p>Borrow principles by channel. Never cosplay an art movement.</p><input id="search" class="search" placeholder="Search Bauhaus, Brazil, print, raw, Japan..."/><div id="lineageGrid" class="lineage"></div></section></main></div><script>
const state={dna:null,catalog:[]};const compositions=['editorial-split','asymmetric-anchor','dense-grid','freeform-collage','vertical-narrative','diagonal-flow','layered-canvas','modular-poster','scroll-choreography','brutalist-index','specimen-sheet','magazine-spread'];const axisLabels={density:'Density',experimentation:'Experimentation',rawness:'Rawness',layering:'Layering',asymmetry:'Asymmetry',kinetic:'Motion',physicality:'Physicality',typographicExpression:'Type expression',contrast:'Contrast',texture:'Texture'};const noveltyLabels={overall:'Overall',layout:'Layout',typography:'Typography',motion:'Motion',color:'Color',navigation:'Navigation',interaction:'Interaction',imagery:'Imagery',texture:'Texture'};const el=id=>document.getElementById(id);
function row(key,label,obj){const wrap=document.createElement('div');wrap.className='row';wrap.innerHTML='<label>'+label+'</label><input type="range" min="0" max="1" step="0.05"><output></output>';const input=wrap.querySelector('input'),out=wrap.querySelector('output');input.value=obj[key];const paint=()=>{obj[key]=Number(input.value);out.textContent=Math.round(obj[key]*100)+'%';renderPreview()};input.addEventListener('input',paint);paint();return wrap}
function renderControls(){el('concept').value=state.dna.concept;el('composition').innerHTML=compositions.map(c=>'<option '+(c===state.dna.composition?'selected':'')+'>'+c+'</option>').join('');el('axesRows').replaceChildren(...Object.entries(axisLabels).map(([k,v])=>row(k,v,state.dna.axes)));el('noveltyRows').replaceChildren(...Object.entries(noveltyLabels).map(([k,v])=>row(k,v,state.dna.novelty)));renderLineage();renderPreview()}
function selected(id){return state.dna.visualLineage.find(x=>x.referenceId===id)}
function renderLineage(){const q=el('search').value.toLowerCase().trim();const refs=state.catalog.filter(r=>!q||[r.id,r.name,r.category,r.profile,...(r.regions||[]),...r.tags].join(' ').toLowerCase().includes(q)).slice(0,80);el('lineageGrid').innerHTML='';refs.forEach(ref=>{const sel=selected(ref.id);const card=document.createElement('article');card.className='ref'+(sel?' selected':'');card.innerHTML='<h3>'+ref.name+'</h3><small>'+ref.category+' · '+(ref.period||'')+'</small><p>'+ref.principles.slice(0,2).join(' · ')+'</p><div class="channels">'+ref.primaryChannels.join(' / ')+'</div><button style="margin-top:10px">'+(sel?'REMOVE':'ADD')+'</button>'+(sel?'<input class="weight" type="range" min="0.05" max="1" step="0.05" value="'+sel.weight+'">':'');card.querySelector('button').onclick=()=>{if(sel)state.dna.visualLineage=state.dna.visualLineage.filter(x=>x.referenceId!==ref.id);else state.dna.visualLineage.push({referenceId:ref.id,weight:.35,borrow:ref.primaryChannels.slice(0,3)});renderLineage();renderPreview()};const weight=card.querySelector('.weight');if(weight)weight.oninput=e=>{selected(ref.id).weight=Number(e.target.value);renderPreview()};el('lineageGrid').append(card)})}
function renderPreview(){if(!state.dna)return;el('previewTitle').textContent=state.dna.concept.split(/\s+/).slice(0,4).join(' ');el('previewMeta').innerHTML='<b>'+state.dna.composition+'</b><br>'+Math.round(state.dna.axes.asymmetry*100)+'% asymmetry<br>'+Math.round(state.dna.novelty.layout*100)+'% layout novelty<br>'+state.dna.visualLineage.length+' lineage refs'}
async function load(){const r=await fetch('/api/state');const data=await r.json();state.dna=data.dna;state.catalog=data.catalog;renderControls()}el('concept').addEventListener('input',e=>{state.dna.concept=e.target.value;renderPreview()});el('composition').addEventListener('change',e=>{state.dna.composition=e.target.value;renderPreview()});el('search').addEventListener('input',renderLineage);el('reload').onclick=load;el('save').onclick=async()=>{el('status').textContent='saving…';const r=await fetch('/api/state',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(state.dna)});const data=await r.json();el('status').textContent=data.ok?'saved .creative-ui/design-dna.json':'error: '+data.error};document.querySelectorAll('[data-tab]').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===btn));document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('active',x.id===btn.dataset.tab))});load();
</script></body></html>`;

export async function startStudio(options: StudioOptions): Promise<void> {
  const port = options.port ?? 4173;
  const server = createServer(async (req, res) => {
    try {
      if (req.method === "GET" && req.url === "/") { res.writeHead(200, { "content-type": "text/html; charset=utf-8", "cache-control": "no-store" }); return res.end(page); }
      if (req.method === "GET" && req.url === "/api/state") return sendJson(res, { dna: await loadDNA(options.cwd), catalog: visualReferenceCatalog });
      if (req.method === "POST" && req.url === "/api/state") { const dna = designDNASchema.parse(JSON.parse(await readBody(req))); await saveDNA(options.cwd, dna); return sendJson(res, { ok: true }); }
      sendJson(res, { error: "not found" }, 404);
    } catch (error) { sendJson(res, { error: error instanceof Error ? error.message : String(error) }, 400); }
  });
  await new Promise<void>((resolve, reject) => { server.once("error", reject); server.listen(port, "127.0.0.1", () => resolve()); });
  const url = `http://127.0.0.1:${port}`; console.log(`Creative UI Studio: ${url}`); if (options.open !== false) void openBrowser(url);
}
